/**
 * Build the Sandkit API catalog from overrides, official HTML, and declarations.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  groupOfficialByNamespace,
  parseOfficialApiInventory,
} from "./lib/sandkit-html.mjs";
import {
  groupDeclaredByNamespace,
  resolveAlias,
  scanDeclaredSandkitApi,
  scanWorkerNamespaces,
} from "./lib/scan-sandkit-api.mjs";

const API_GEN = dirname(fileURLToPath(import.meta.url));
const ROOT = dirname(dirname(API_GEN));
const OVERRIDES_PATH = join(API_GEN, "overrides.json");
const GENERATED_DIR = join(API_GEN, "generated");
const CATALOG_PATH = join(GENERATED_DIR, "api-catalog.json");
const SUMMARIES_PATH = join(GENERATED_DIR, "namespace-summaries.json");
const GAPS_PATH = join(ROOT, "docs", "generated", "api-gaps.md");
const CACHE_PATH = join(ROOT, ".tmp", "sandkit.html");
const SRC = join(ROOT, "src");

/**
 * @param {string} message
 * @returns {never}
 */
function fail(message) {
  console.error(`api-gen: ${message}`);
  process.exit(1);
}

/**
 * @param {string} url
 */
async function fetchOfficialHtml(url) {
  console.log(`api-gen: fetching ${url}`);
  const response = await fetch(url);
  if (!response.ok) fail(`fetch failed: HTTP ${response.status} ${response.statusText}`);
  const html = await response.text();
  if (!html.includes("api-content")) fail("fetched page does not look like Sandkit docs");
  mkdirSync(dirname(CACHE_PATH), { recursive: true });
  writeFileSync(CACHE_PATH, html);
  return html;
}

/**
 * @param {string} url
 * @param {boolean} offline
 */
async function loadOfficialHtml(url, offline) {
  if (!offline) {
    try {
      return await fetchOfficialHtml(url);
    } catch (err) {
      try {
        const cached = readFileSync(CACHE_PATH, "utf8");
        console.warn(
          `api-gen: fetch failed (${err instanceof Error ? err.message : err}); using cache`,
        );
        return cached;
      } catch {
        fail(err instanceof Error ? err.message : String(err));
      }
    }
  }

  try {
    return readFileSync(CACHE_PATH, "utf8");
  } catch {
    fail(`missing cache ${CACHE_PATH}; run without --offline to fetch official HTML`);
  }
}

/**
 * @param {Set<string>} declaredPaths
 * @param {Record<string, string>} aliases
 * @param {string} path
 */
function isDeclared(declaredPaths, aliases, path) {
  if (declaredPaths.has(path)) return true;
  const aliased = resolveAlias(path, aliases);
  return declaredPaths.has(aliased);
}

/**
 * @param {ReturnType<typeof buildCatalog>} catalog
 */
function renderGapsMarkdown(catalog) {
  const lines = [
    "# API catalog gaps",
    "",
    "Generated by `npm run generate`.",
    "Edit descriptions and expected members in `scripts/api-gen/overrides.json`.",
    "",
    "## Summary",
    "",
    `- Official source: ${catalog.officialSource}`,
    `- Generated: ${catalog.generatedAt}`,
    `- Namespaces: ${catalog.stats.namespaceCount}`,
    `- Official methods (HTML): ${catalog.stats.officialMethodCount}`,
    `- Declared methods (types): ${catalog.stats.declaredMethodCount}`,
    `- Open gaps: ${catalog.stats.openGapCount}`,
    "",
  ];

  const gapNamespaces = Object.entries(catalog.namespaces)
    .filter(([, ns]) => ns.gaps.length > 0)
    .sort((a, b) => b[1].gaps.length - a[1].gaps.length);

  if (!gapNamespaces.length) {
    lines.push("No open gaps.", "");
    return `${lines.join("\n")}`;
  }

  lines.push("## Gaps by namespace", "");

  for (const [name, ns] of gapNamespaces) {
    lines.push(`### ${name}`, "");
    for (const gap of ns.gaps) {
      lines.push(`- \`${gap.path}\`${gap.note ? ` — ${gap.note}` : ""}`);
    }
    lines.push("");
  }

  return `${lines.join("\n")}`;
}

/**
 * @param {string} html
 * @param {object} overrides
 */
function buildCatalog(html, overrides) {
  const officialMembers = parseOfficialApiInventory(html);
  const officialByNs = groupOfficialByNamespace(officialMembers);
  const declaredMembers = scanDeclaredSandkitApi(SRC);
  const declaredByNs = groupDeclaredByNamespace(declaredMembers);
  const declaredPaths = new Set(declaredMembers.map((m) => m.path));
  const workerFromTypes = scanWorkerNamespaces(SRC);

  /** @type {Record<string, string>} */
  const aliases = overrides.aliases ?? {};
  /** @type {Array<{ path: string, note?: string }>} */
  const expectedMembers = overrides.expectedMembers ?? [];

  const namespaceNames = new Set([
    ...Object.keys(overrides.namespaces ?? {}),
    ...Object.keys(officialByNs),
    ...Object.keys(declaredByNs),
  ]);

  /** @type {Record<string, object>} */
  const namespaces = {};
  let openGapCount = 0;

  for (const name of [...namespaceNames].sort()) {
    const override = overrides.namespaces?.[name] ?? {};
    const official = officialByNs[name] ?? [];
    const declared = declaredByNs[name] ?? [];

    const officialPaths = [...new Set(official.map((m) => m.path))];
    const declaredPathsForNs = [...new Set(declared.map((m) => m.path))];

    /** @type {Array<{ path: string, note?: string, source: string }>} */
    const gaps = [];

    for (const path of officialPaths) {
      if (!isDeclared(declaredPaths, aliases, path)) {
        gaps.push({ path, source: "official" });
      }
    }

    for (const entry of expectedMembers) {
      if (!entry.path.startsWith(`${name}.`) && entry.path.split(".")[0] !== name) continue;
      if (!isDeclared(declaredPaths, aliases, entry.path)) {
        gaps.push({ path: entry.path, note: entry.note, source: "expected" });
      }
    }

    const deduped = [];
    const seen = new Set();
    for (const gap of gaps) {
      if (seen.has(gap.path)) continue;
      seen.add(gap.path);
      deduped.push(gap);
    }
    openGapCount += deduped.length;

    namespaces[name] = {
      description: override.description ?? "",
      worker: override.worker ?? workerFromTypes.has(name),
      methodCount: {
        official: officialPaths.length,
        declared: declaredPathsForNs.length,
      },
      officialMethods: officialPaths.sort(),
      declaredMethods: declaredPathsForNs.sort(),
      gaps: deduped,
    };
  }

  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    officialSource: overrides.officialUrl ?? "https://sandustry.com/sandkit.html",
    stats: {
      namespaceCount: namespaceNames.size,
      officialMethodCount: officialMembers.length,
      declaredMethodCount: declaredMembers.length,
      openGapCount,
    },
    namespaces,
  };
}

/**
 * @param {ReturnType<typeof buildCatalog>} catalog
 */
function buildNamespaceSummaries(catalog) {
  /** @type {Record<string, { description: string, worker: boolean }>} */
  const out = {};
  for (const [name, ns] of Object.entries(catalog.namespaces)) {
    out[name] = {
      description: ns.description,
      worker: ns.worker,
    };
  }
  return out;
}

/**
 * @param {string} path
 * @param {string} next
 * @param {boolean} check
 */
function writeIfChanged(path, next, check) {
  let prev = null;
  try {
    prev = readFileSync(path, "utf8");
  } catch {
    // new file
  }
  if (check) {
    if (prev !== next) fail(`stale file: ${path} (run npm run generate)`);
    return;
  }
  writeFileSync(path, next);
}

/**
 * @param {{ offline?: boolean, check?: boolean }} [options]
 */
export async function runCatalog(options = {}) {
  const { offline = false, check = false } = options;
  const overrides = JSON.parse(readFileSync(OVERRIDES_PATH, "utf8"));
  const html = await loadOfficialHtml(overrides.officialUrl, offline);
  const catalog = buildCatalog(html, overrides);
  const summaries = buildNamespaceSummaries(catalog);
  const gapsMd = renderGapsMarkdown(catalog);

  mkdirSync(GENERATED_DIR, { recursive: true });
  mkdirSync(dirname(GAPS_PATH), { recursive: true });

  writeIfChanged(CATALOG_PATH, `${JSON.stringify(catalog, null, 2)}\n`, check);
  writeIfChanged(SUMMARIES_PATH, `${JSON.stringify(summaries, null, 2)}\n`, check);
  writeIfChanged(GAPS_PATH, gapsMd, check);

  if (check) {
    console.log("api-gen: catalog ok (outputs up to date)");
    return catalog;
  }

  console.log(`api-gen: wrote ${CATALOG_PATH}`);
  console.log(`api-gen: wrote ${SUMMARIES_PATH}`);
  console.log(`api-gen: wrote ${GAPS_PATH}`);
  console.log(
    `api-gen: ${catalog.stats.officialMethodCount} official, ${catalog.stats.declaredMethodCount} declared, ${catalog.stats.openGapCount} gaps`,
  );
  return catalog;
}
