/**
 * Main-thread `sandkit.api` barrel.
 *
 * Re-exports all namespaces available as `sandkit.api.*` on the main thread.
 * Prefer these methods over {@link sandkit.engine} when both exist.
 *
 * @module
 */

export * from "./action"
export * from "./assets"
export * from "./authorization"
export * from "./building"
export * from "./camera"
export * from "./collector"
export * from "./constants"
export * from "./cooldown"
export * from "./discoveries"
export * from "./effects"
export * from "./elements"
export * from "./energy"
export * from "./events"
export * from "./excavation"
export * from "./fire"
export * from "./gameconfig"
export * from "./grid"
export * from "./hooks"
export * from "./i18n"
export * from "./input"
export * from "./items"
export * from "./lights"
export * from "./maps"
export * from "./mods"
export * from "./patterns"
export * from "./player"
export * from "./processing"
export * from "./progression"
export * from "./projectiles"
export * from "./random"
export * from "./raycast"
export * from "./reactions"
export * from "./rendering"
export * from "./resources"
export * from "./scene"
export * from "./schedule"
export * from "./settings"
export * from "./shared"
export * from "./signals"
export * from "./sound"
export * from "./sprites"
export * from "./storage"
export * from "./structureBehaviors"
export * from "./structures"
export * from "./tech"
export * from "./terrains"
export * from "./time"
export * from "./tools"
export * from "./triggers"
export * from "./ui"
export * from "./upgrades"
export * from "./utils"
export * from "./workers"
export * from "./world"

/** Composed type of the main-thread `sandkit.api` object. */
export type { SandkitApi } from "./sandkit-api"
